name: Build

on:
  pull_request:
    branches: [main]
    paths:
      - src/**.*
      - premake5.lua

jobs:
  build-windows:
    name: Build Windows
    runs-on: windows-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2

      - name: Run Premake
        run: vendor/premake/premake5.exe vs2019

      - name: Add MSBuild to PATH
        uses: microsoft/setup-msbuild@v1.0.2

      - name: Build
        working-directory: ${{ env.GITHUB_WORKSPACE }}
        run: msbuild /m /p:Configuration=Release build

  build-linux:
    name: Build Linux
    runs-on: ubuntu-latest

    env:
      CC: gcc-10
      CXX: g++-10

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2

      - name: Install Dependencies
        run: |
          sudo apt update
          sudo apt install gcc-10 g++-10

      - name: Run Premake
        run: vendor/premake/premake5 gmake2

      - name: Build
        run: make -C build config=release
